AWSTemplateFormatVersion: 2010-09-09
Description: |
  This template launches Kittens Carousel Static Website ec2 instance with a SG which enables SSH.
  
Resources:
  KCSWInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-05fa00d4c63e32376
      InstanceType: t2.micro
      KeyName: gen-1-ugur # Please use your key pair name without pem.
      SecurityGroups:
        - !Ref KCSWSecGroup
      Tags:
        - Key: Name
          Value: First-KCSW-Instance
      UserData:
        Fn::Base64: 
          !Sub |
            #!/bin/bash
            yum update -y
            yum install git -y
            yum install httpd -y
            systemctl start httpd
            systemctl enable httpd
            git clone https://github.com/th3n3xtg3n3ration/my-projects.git
            cd my-projects/Project-101-kittens-carousel-static-website-ec2/static-web/
            cp * /var/www/html/

  KCSWSecGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enables SSH for KCSW Instance # Required
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0